version: "3"
services:
  memory:
    image: ghcr.io/morten-olsen/memory
    build: '.'
    container_name: memory
    restart: unless-stopped
    environment:
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
      - LOG_LEVEL=verbose
      - EXPO_ACCESS_TOKEN=${EXPO_ACCESS_TOKEN}
    volumes:
      - "$FAST_STORAGE/olli/data:/data"
    networks:
      - loadbalancer
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.memory.rule=Host(`olli.$DOMAIN`)"
      - "traefik.http.routers.memory.entrypoints=websecure"
      - "traefik.http.routers.memory.tls.domains[0].main=$DOMAIN"
      - "traefik.http.routers.memory.tls.domains[0].sans=*.$DOMAIN"
      - "traefik.http.routers.memory.tls.certresolver=mydnschallenge"
      - "traefik.http.services.memory.loadbalancer.server.port=4000"
networks:
  loadbalancer:
    name: loadbalancer
